# Generated by Django 3.1.7 on 2021-03-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('family_cnt', models.IntegerField()),
                ('C', models.IntegerField()),
                ('Q', models.IntegerField()),
                ('S', models.IntegerField()),
                ('predicted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
