# Generated by Django 3.1.7 on 2021-03-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_predictions_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictions',
            name='C',
        ),
        migrations.RemoveField(
            model_name='predictions',
            name='Q',
        ),
        migrations.RemoveField(
            model_name='predictions',
            name='S',
        ),
        migrations.AddField(
            model_name='predictions',
            name='Embarked',
            field=models.CharField(default='', max_length=30),
        ),
    ]
